### ISSUE TITLE
Support for Legacy IE78?

### ISSUE THREAD

**Issue by rareyman** [VuongN/jQuery-Fakecrop#2]
Yeah, I know. Who cares about IE7&8, right? Sadly, my clients demand support for those ancient browsers, so I have to figure out a way to appease them.

I don't mind rolling up my sleeves, forking this project and making edits myself, I just was wondering if anyone could point me in the right direction of where I could modify a few lines to make this work in IE7&8…

Thanks!

**Comment by VuongN** [comment]
Hi @rareyman! Yeah, really sorry I haven't been able to pay much attention to this plugin in a while. To be honest, I haven't even tried looking at it on IE7. But I do understand your pain. Now you get me all curious, I really wonder how terrible it looks in IE7,8.  There is not much to this plugin though so just fire it up on IE7, mess with the stuff until it looks right. It will most likely be a css issue as the javascript in this plugin isn't all that complicated--just some simple math. Let me know how it goes. Good luck!

-Vuong

**Comment by rareyman** [comment]
Right on! I hope to fork it soon and mess around with the code and see how it goes. Any ideas on best practices for isolating ie7 and ie8 in modern versions of jquery?!?

**Comment by VuongN** [comment]
I think it's fair to say, we'll close this for now. I don't think anyone should be supporting IE7 or 8 at this point.
